### ISSUE TITLE
Minimalist Dark and Yellow Tabs Missing and Redired to Everforest

### ISSUE THREAD

**Issue by TheProfosist** [canbeardig/MinimalistFox#2]
I loved the "Minimalist Dark and Yellow Tabs" theme and have been running it for years but a couple of days ago things updated and it no longer exists. I was wondering if you could make it available again or create a separate one that doesn't get redirected. I noticed it as changed, in one case at work right before my eyes!

**Comment by canbeardig** [comment]
Hi. My plan was to match the color schemes since the beginning and recently I have been updating the themes with the small changes. And If I upload a new theme with similar colors, it will get deleted by the mod team. You can still download the xpi files of the previous versions from [this link.](https://onedrive.live.com/?authkey=%21ADE9m3Ax4UyoH2g&id=8F9BBCABFF5DB091%214984&cid=8F9BBCABFF5DB091) Opening the xpi file with firefox will install the theme.

**Comment by TheProfosist** [comment]
Appreciate it! I downloaded the whole folder, thanks!
