### ISSUE TITLE
Illegible text on active tabs on Floorp Browser

### ISSUE THREAD

**Issue by rustic02** [canbeardig/MinimalistFox#3]
The text on active tab is not readable on minimalist gruvbox, the active tab also does not turn green while it works fine on firefox. This issue is same with minimalist nord.
![Screenshot_20241228_202622](https://github.com/user-attachments/assets/387f9814-b8e7-47c1-8165-842a4b68a1b6)

**Comment by canbeardig** [comment]
The themes work on other forks of Firefox including Waterfox, Librewolf and Tor Browser. It seeems the issue is with Floorp browser. It doesn't support "tab_selected" colour on any themes. A theme from Mozilla with a white tab on both Firefox and Floorp below.

![Capture1](https://github.com/user-attachments/assets/840639e4-fa6f-42ff-a0b4-0383f07997e0)

![Capture2](https://github.com/user-attachments/assets/daff439a-1622-4bb5-b4b8-7c40cc897687)

**Comment by rustic02** [comment]
yeah, i checked it right now. there are three browser appearance modes in Floorp. Theme works fine on `Firefox Proton UI` and does not work on `Lepton UI` and `Floorp Fluerial UI`.
